const express = require('express');
const path = require('path');
const crypto = require('crypto');

const app = express();
app.disable('x-powered-by');
app.post('/api/webhooks/razorpay', express.raw({ type: 'application/json' }), verifyWebhook);
app.use(express.json({ limit: '100kb' }));

const weights = { intent: .30, price: .20, delivery: .15, merchant: .15, payment: .10, protection: .05, value: .05 };
const id = (prefix) => `${prefix}_${crypto.randomUUID().slice(0, 8)}`;
const now = () => new Date().toISOString();
const intents = new Map(); const payments = new Map(); const webhookEvents = new Set();
const merchants = [
  { id: 'm1', name: 'HomeSphere', color: '#4f46e5', reliability: 89, products: [{ id: 'p1', name: 'WhirlPro 7kg Front Load', price: 27999, capacity: 7, warranty: 2, inventory: 14, delivery: 3, returns: 7 }] },
  { id: 'm2', name: 'Reliance Digital Demo', color: '#0f766e', reliability: 96, products: [{ id: 'p2', name: 'AquaWash 7kg Smart Front Load', price: 29499, capacity: 7, warranty: 3, inventory: 9, delivery: 2, returns: 10 }, { id: 'p3', name: 'SprintRun Pro Shoe', price: 4699, size: 9, inventory: 30, delivery: 2, returns: 14 }] },
  { id: 'm3', name: 'ValueKart Supply', color: '#ea580c', reliability: 93, products: [{ id: 'p4', name: 'WashMate 7.2kg Top Load', price: 26899, capacity: 7.2, warranty: 2, inventory: 21, delivery: 4, returns: 7 }, { id: 'p5', name: 'Custom Cotton T-Shirt (500 pack)', price: 76500, quantity: 500, inventory: 4, delivery: 8, returns: 0 }] },
  { id: 'm4', name: 'Urban Fabric Co.', color: '#be123c', reliability: 91, products: [{ id: 'p6', name: 'Custom Cotton T-Shirt (500 pack)', price: 79200, quantity: 500, inventory: 7, delivery: 7, returns: 0 }, { id: 'p7', name: 'Everyday Runner Shoe', price: 4499, size: 9, inventory: 16, delivery: 3, returns: 10 }] }
];
function audit(record, event, detail, kind = 'info') { record.timeline.push({ id: id('evt'), at: now(), event, detail, kind }); }
function deterministicParse(rawText) { const text = rawText.toLowerCase(); const match = [...text.matchAll(/\b(\d[\d,]*(?:\.\d+)?)\s*(k|thousand|hazaar|lakh)\b/g)][0] || text.match(/(?:₹|rs\.?|inr)\s*(\d[\d,]*(?:\.\d+)?)/); let budgetMax = match ? Number(String(match[1]).replaceAll(',', '')) : 30000; if (['k', 'thousand', 'hazaar'].includes(match?.[2])) budgetMax *= 1000; if (match?.[2] === 'lakh') budgetMax *= 100000; const category = /wash|machine/.test(text) ? 'washing_machine' : /shoe|running|sneaker/.test(text) ? 'running_shoes' : /shirt|tee/.test(text) ? 'custom_tshirts' : 'home_essentials'; return { category, budgetMax: Math.round(budgetMax), capacityMin: Number((text.match(/(\d+(?:\.\d+)?)\s*kg/) || [])[1]) || null, size: Number((text.match(/size\s*(\d+)/) || [])[1]) || null, warrantyMin: /2.?year|2.?saal/.test(text) ? 2 : 0, quantity: category === 'custom_tshirts' ? Number((text.match(/(\d+)\s*(?:custom|t.?shirt|pieces?)/) || [])[1]) || 500 : 1, deadline: /sunday|kal|tomorrow/.test(text) ? 3 : 10, returnRequired: /return/.test(text), priority: /reliab|safe/.test(text) ? 'successful_fulfillment' : 'best_value' }; }
async function parseIntent(rawText) { const fallback = deterministicParse(rawText); if (!process.env.OPENAI_API_KEY) return { data: fallback, source: 'deterministic-fallback', reason: 'OPENAI_API_KEY not configured' }; const schema = { type: 'object', additionalProperties: false, required: ['category', 'budgetMax', 'capacityMin', 'size', 'warrantyMin', 'quantity', 'deadline', 'returnRequired', 'priority'], properties: { category: { type: 'string', enum: ['washing_machine', 'running_shoes', 'custom_tshirts', 'home_essentials'] }, budgetMax: { type: 'integer', minimum: 1 }, capacityMin: { type: ['number', 'null'] }, size: { type: ['integer', 'null'] }, warrantyMin: { type: 'integer', minimum: 0 }, quantity: { type: 'integer', minimum: 1 }, deadline: { type: 'integer', minimum: 1 }, returnRequired: { type: 'boolean' }, priority: { type: 'string', enum: ['best_value', 'successful_fulfillment'] } } }; try { const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.OPENAI_MODEL || 'gpt-5', store: false, instructions: 'Extract only purchase constraints. Never approve a payment, recommend a merchant, or invent facts.', input: rawText, text: { format: { type: 'json_schema', name: 'purchase_intent', strict: true, schema } } }) }); if (!response.ok) throw new Error(`OpenAI request failed (${response.status})`); const result = await response.json(); return { data: { ...fallback, ...JSON.parse(result.output_text) }, source: 'openai-structured-output' }; } catch (error) { return { data: fallback, source: 'deterministic-fallback', reason: error.message }; } }
function rank(intent, simulation = 'none') { const matches = (product) => intent.category === 'washing_machine' ? /wash/i.test(product.name) : intent.category === 'running_shoes' ? /shoe/i.test(product.name) : intent.category === 'custom_tshirts' ? /shirt/i.test(product.name) : false; return merchants.flatMap((merchant) => merchant.products.map((product) => ({ ...product, merchant }))).filter(matches).map(({ merchant, ...product }) => { const price = simulation === 'price_drift' && product.id === 'p2' ? 57999 : product.price; const inventory = simulation === 'inventory_failure' && product.id === 'p2' ? 0 : product.inventory; const reasons = []; if (price > intent.budgetMax) reasons.push('Price exceeds the user-approved budget'); if (inventory < intent.quantity) reasons.push('Inventory is no longer available'); if (intent.capacityMin && product.capacity < intent.capacityMin) reasons.push('Capacity does not meet the requirement'); if (intent.warrantyMin && (product.warranty || 0) < intent.warrantyMin) reasons.push('Warranty does not meet the requirement'); if (intent.returnRequired && !product.returns) reasons.push('Return policy is required'); if (product.delivery > intent.deadline) reasons.push('Delivery misses the requested deadline'); const eligible = reasons.length === 0; const priceValue = Math.max(0, 100 - Math.max(0, price / intent.budgetMax * 100 - 70) * 1.2); const intentFit = eligible ? Math.min(100, 86 + (product.capacity >= intent.capacityMin ? 7 : 0) + (product.warranty >= intent.warrantyMin ? 4 : 0)) : 0; const score = eligible ? Math.round(intentFit * weights.intent + priceValue * weights.price + (100 - product.delivery * 11) * weights.delivery + merchant.reliability * (weights.merchant + weights.payment + weights.protection) + 90 * weights.value) : 0; return { id: id('offer'), productId: product.id, merchantId: merchant.id, merchant: merchant.name, product: product.name, price, inventory, delivery: product.delivery, warranty: product.warranty || 0, returns: product.returns || 0, eligible, reasons, score, color: merchant.color, explanation: eligible ? 'Meets all hard constraints. Score balances requirement fit, value, delivery, and merchant reliability.' : reasons.join('. ') }; }).sort((a, b) => b.score - a.score); }
function razorpayEnabled() { return Boolean(process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET); }
async function createProviderOrder(payment) { if (!razorpayEnabled()) return { id: `order_demo_${crypto.randomUUID().slice(0, 10)}`, provider: 'mock' }; const auth = Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString('base64'); const response = await fetch('https://api.razorpay.com/v1/orders', { method: 'POST', headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ amount: payment.amount * 100, currency: 'INR', receipt: payment.id, notes: { intent_id: payment.intentId, offer_id: payment.offerId } }) }); if (!response.ok) throw new Error(`Razorpay order creation failed (${response.status})`); return { ...(await response.json()), provider: 'razorpay' }; }
function safeEqual(left, right) { const a = Buffer.from(left || ''); const b = Buffer.from(right || ''); return a.length === b.length && crypto.timingSafeEqual(a, b); }
app.get('/health', (_req, res) => res.json({ status: 'ok', service: 'Intent Exchange', mode: razorpayEnabled() ? 'razorpay-test-ready' : 'demo', ai: process.env.OPENAI_API_KEY ? 'configured' : 'deterministic-fallback' }));
app.get('/api/config', (_req, res) => res.json({ paymentMode: razorpayEnabled() ? 'razorpay' : 'mock', keyId: razorpayEnabled() ? process.env.RAZORPAY_KEY_ID : null, aiMode: process.env.OPENAI_API_KEY ? 'openai' : 'deterministic-fallback' }));
app.post('/api/intents', async (req, res) => { const rawText = String(req.body.rawText || '').trim(); if (rawText.length < 8) return res.status(400).json({ error: 'Please describe what you need in a little more detail.' }); const parsed = await parseIntent(rawText); const intent = { id: id('intent'), rawText, ...parsed.data, createdAt: now(), authorization: null, offers: [], timeline: [] }; audit(intent, 'INTENT RECEIVED', 'Buyer request recorded.'); audit(intent, 'CONSTRAINTS EXTRACTED', parsed.source + (parsed.reason ? ` (${parsed.reason})` : '')); intents.set(intent.id, intent); res.status(201).json({ intent, parser: parsed.source }); });
app.post('/api/intents/:id/search', (req, res) => { const intent = intents.get(req.params.id); if (!intent) return res.status(404).json({ error: 'Intent not found.' }); const offers = rank(intent, req.body.simulation || 'none'); const winner = offers.find((offer) => offer.eligible); intent.offers = offers; audit(intent, 'OFFERS EVALUATED', `${offers.length} offers evaluated against hard constraints.`); audit(intent, 'RECOMMENDATION EXPLAINED', winner ? `${winner.merchant} is best eligible offer; no payment action taken.` : 'No eligible offer found.', winner ? 'info' : 'warning'); res.json({ intent, offers, winner, explanation: winner ? `${winner.merchant} is recommended because it meets every hard constraint. Payment is still blocked until explicit user approval.` : 'No offer meets every hard constraint.' }); });
app.post('/api/purchases/authorize', (req, res) => { const intent = intents.get(req.body.intentId); const offer = intent?.offers.find((item) => item.id === req.body.offerId); if (!offer?.eligible) return res.status(409).json({ error: 'This offer cannot be authorized. Re-run discovery to select an eligible offer.' }); intent.authorization = { id: id('auth'), offerId: offer.id, maxAmount: offer.price, status: 'AUTHORIZED', at: now() }; audit(intent, 'USER AUTHORIZED SPEND', `Buyer explicitly approved up to ₹${offer.price.toLocaleString('en-IN')} for ${offer.product}.`); res.json({ authorization: intent.authorization, timeline: intent.timeline }); });
app.post('/api/payments/create-order', async (req, res, next) => { try { const intent = intents.get(req.body.intentId); const key = String(req.body.idempotencyKey || '').trim(); if (!intent?.authorization || intent.authorization.offerId !== req.body.offerId) return res.status(403).json({ error: 'Explicit user authorization is required before payment.' }); if (!key) return res.status(400).json({ error: 'An idempotencyKey is required.' }); const offer = intent.offers.find((item) => item.id === req.body.offerId); if (!offer) return res.status(404).json({ error: 'Selected offer is no longer available.' }); const existing = [...payments.values()].find((item) => item.idempotencyKey === key); if (existing) return res.json({ payment: existing, reused: true }); const payment = { id: id('pay'), intentId: intent.id, offerId: offer.id, amount: offer.price, currency: 'INR', idempotencyKey: key, status: 'ORDER_CREATING', verificationStatus: 'PENDING', createdAt: now(), timeline: [...intent.timeline] }; const order = await createProviderOrder(payment); payment.razorpayOrderId = order.id; payment.provider = order.provider; payment.status = 'PAYMENT_PENDING'; audit(payment, 'PAYMENT ORDER CREATED', order.provider === 'razorpay' ? 'Razorpay test-mode order created on the server.' : 'Mock order created. Add Razorpay test keys to enable checkout.'); payments.set(payment.id, payment); res.status(201).json({ payment, checkout: order.provider === 'razorpay' ? { keyId: process.env.RAZORPAY_KEY_ID, orderId: order.id } : null }); } catch (error) { next(error); } });
app.post('/api/payments/:id/verify', (req, res) => { const payment = payments.get(req.params.id); if (!payment) return res.status(404).json({ error: 'Payment not found.' }); if (payment.provider !== 'razorpay') return res.status(409).json({ error: 'This endpoint verifies Razorpay checkout payments only.' }); const expected = crypto.createHmac('sha256', process.env.RAZORPAY_KEY_SECRET).update(`${payment.razorpayOrderId}|${req.body.razorpay_payment_id || ''}`).digest('hex'); if (!safeEqual(expected, req.body.razorpay_signature)) { payment.status = 'REJECTED'; audit(payment, 'SIGNATURE VERIFICATION FAILED', 'Payment was rejected; no fulfilment action was performed.', 'danger'); return res.status(400).json({ error: 'Signature verification failed. Payment was not accepted.', payment }); } payment.status = 'VERIFIED'; payment.verificationStatus = 'VERIFIED'; payment.razorpayPaymentId = req.body.razorpay_payment_id; audit(payment, 'SIGNATURE VERIFIED', 'Server-side signature verification passed. Awaiting merchant fulfilment.'); res.json({ payment }); });
app.post('/api/payments/:id/simulate', (req, res) => { const payment = payments.get(req.params.id); const outcome = req.body.outcome || 'success'; if (!payment) return res.status(404).json({ error: 'Payment not found.' }); if (!['success', 'failure', 'order_failure'].includes(outcome)) return res.status(400).json({ error: 'outcome must be success, failure, or order_failure.' }); if (outcome === 'failure') { payment.status = 'PAYMENT_FAILED'; audit(payment, 'PAYMENT FAILED', 'Simulated decline. User has not been charged.', 'danger'); } else { payment.status = outcome === 'order_failure' ? 'RECOVERY_REQUIRED' : 'FULFILLED'; payment.verificationStatus = 'SIMULATED'; audit(payment, 'PAYMENT SUCCESS', 'Simulated payment success in demo mode.'); audit(payment, outcome === 'order_failure' ? 'RECOVERY REQUIRED' : 'ORDER FULFILLED', outcome === 'order_failure' ? 'Merchant confirmation is missing. Manual recovery queue opened.' : 'Merchant order confirmed.'); } res.json({ payment }); });
app.get('/api/transactions/:id', (req, res) => { const payment = payments.get(req.params.id); if (!payment) return res.status(404).json({ error: 'Transaction not found.' }); res.json({ payment, intent: intents.get(payment.intentId) }); });
function verifyWebhook(req, res) { const signature = req.get('x-razorpay-signature'); const raw = req.body; if (!process.env.RAZORPAY_WEBHOOK_SECRET) return res.status(503).json({ error: 'Webhook secret is not configured.' }); const expected = crypto.createHmac('sha256', process.env.RAZORPAY_WEBHOOK_SECRET).update(raw).digest('hex'); if (!safeEqual(expected, signature)) return res.status(400).json({ error: 'Invalid webhook signature.' }); const event = JSON.parse(raw.toString('utf8')); const eventId = event.event + event.payload?.payment?.entity?.id; if (webhookEvents.has(eventId)) return res.status(200).json({ received: true, duplicate: true }); webhookEvents.add(eventId); const providerOrderId = event.payload?.payment?.entity?.order_id; const payment = [...payments.values()].find((item) => item.razorpayOrderId === providerOrderId); if (payment) audit(payment, `WEBHOOK: ${event.event}`, 'Verified Razorpay webhook received.'); return res.status(200).json({ received: true }); }
app.use(express.static(path.join(__dirname, '..', 'public'))); app.use((req, res, next) => req.method === 'GET' ? res.sendFile(path.join(__dirname, '..', 'public', 'index.html')) : next()); app.use((error, _req, res, _next) => res.status(500).json({ error: error.message || 'Something went wrong. Please try again.' }));
module.exports = { app, deterministicParse, rank };
